/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * AI Agent API
 * The AI Agent API description
 * OpenAPI spec version: 1.0
 */

export interface AccommodationDto {
  /** Name of the accommodation */
  name: string;
  /** Address of the accommodation */
  address: string;
  /** Check-in time */
  checkIn: string;
  /** Check-out time */
  checkOut: string;
  /** Price of the accommodation */
  price: string;
}
