/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * AI Agent API
 * The AI Agent API description
 * OpenAPI spec version: 1.0
 */

/**
 * Type of activity
 */
export type ActivityDtoType = (typeof ActivityDtoType)[keyof typeof ActivityDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActivityDtoType = {
  attraction: 'attraction',
  meal: 'meal',
  other: 'other',
} as const;
