/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * AI Agent API
 * The AI Agent API description
 * OpenAPI spec version: 1.0
 */

export interface ConversationResponseDto {
  /** The unique identifier of the conversation */
  id: number;
  /** The timestamp when the conversation was created */
  createdAt: string;
  /** The timestamp when the conversation was last updated */
  updatedAt: string;
}
