/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * AI Agent API
 * The AI Agent API description
 * OpenAPI spec version: 1.0
 */
import type { MessageResponseDtoRole } from './messageResponseDtoRole';

export interface MessageResponseDto {
  /** The unique identifier of the message */
  id: number;
  /** The ID of the conversation this message belongs to */
  conversationId: number;
  /** The role of the message sender */
  role: MessageResponseDtoRole;
  /** The content of the message */
  content: string;
  /** The name of the function (only for function messages) */
  name?: string;
  /** The timestamp when the message was created */
  createdAt: string;
}
