/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * AI Agent API
 * The AI Agent API description
 * OpenAPI spec version: 1.0
 */

/**
 * The role of the message sender
 */
export type MessageResponseDtoRole = typeof MessageResponseDtoRole[keyof typeof MessageResponseDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageResponseDtoRole = {
  user: 'user',
  assistant: 'assistant',
  function: 'function',
} as const;
