/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * AI Agent API
 * The AI Agent API description
 * OpenAPI spec version: 1.0
 */

export interface MessageRequestDto {
  /** The message to send to the agent */
  message: string;
}
